// Generated by gencpp from file probot_grasping/Position.msg
// DO NOT EDIT!


#ifndef PROBOT_GRASPING_MESSAGE_POSITION_H
#define PROBOT_GRASPING_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace probot_grasping
{
template <class ContainerAllocator>
struct Position_
{
  typedef Position_<ContainerAllocator> Type;

  Position_()
    : u(0)
    , v(0)  {
    }
  Position_(const ContainerAllocator& _alloc)
    : u(0)
    , v(0)  {
  (void)_alloc;
    }



   typedef uint16_t _u_type;
  _u_type u;

   typedef uint16_t _v_type;
  _v_type v;





  typedef boost::shared_ptr< ::probot_grasping::Position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::probot_grasping::Position_<ContainerAllocator> const> ConstPtr;

}; // struct Position_

typedef ::probot_grasping::Position_<std::allocator<void> > Position;

typedef boost::shared_ptr< ::probot_grasping::Position > PositionPtr;
typedef boost::shared_ptr< ::probot_grasping::Position const> PositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::probot_grasping::Position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::probot_grasping::Position_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::probot_grasping::Position_<ContainerAllocator1> & lhs, const ::probot_grasping::Position_<ContainerAllocator2> & rhs)
{
  return lhs.u == rhs.u &&
    lhs.v == rhs.v;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::probot_grasping::Position_<ContainerAllocator1> & lhs, const ::probot_grasping::Position_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace probot_grasping

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::probot_grasping::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::probot_grasping::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_grasping::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_grasping::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_grasping::Position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_grasping::Position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::probot_grasping::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a9741b956dcfa783be9a0d5a4a2446e";
  }

  static const char* value(const ::probot_grasping::Position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a9741b956dcfa78ULL;
  static const uint64_t static_value2 = 0x3be9a0d5a4a2446eULL;
};

template<class ContainerAllocator>
struct DataType< ::probot_grasping::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "probot_grasping/Position";
  }

  static const char* value(const ::probot_grasping::Position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::probot_grasping::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 u\n"
"uint16 v\n"
;
  }

  static const char* value(const ::probot_grasping::Position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::probot_grasping::Position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.u);
      stream.next(m.v);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::probot_grasping::Position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::probot_grasping::Position_<ContainerAllocator>& v)
  {
    s << indent << "u: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.u);
    s << indent << "v: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.v);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROBOT_GRASPING_MESSAGE_POSITION_H
